### ISSUE TITLE
guidance request

### ISSUE THREAD

**Issue by forouzanbeydaghi** [lok-i/DRLPathPlanner#2]
Hi

I want to change the code so that the agent is exactly at the green goal square (similar to the figure attached to the link).
Please advise what change should I make in the code?

best regard

https://iutbox.iut.ac.ir/index.php/s/AmaKpKdDEEGnS5k

**Comment by lok-i** [comment]
Hi @forouzanbeydaghi,

For obtaining such a visual render (as sown in this link by you https://iutbox.iut.ac.ir/index.php/s/AmaKpKdDEEGnS5k), you should simply call the env.render() statement after the env.step() statement in any required file. For example, you can place this line, https://github.com/lok-i/DRLPathPlanner/blob/5bb6694f3fbf53a2aa79b9195cdfe89caee597ea/DPP-v1/Test_Model.py#L66 after the line, https://github.com/lok-i/DRLPathPlanner/blob/5bb6694f3fbf53a2aa79b9195cdfe89caee597ea/DPP-v1/Test_Model.py#L69 in the file [./DPP-v1/Test_Model.py](https://github.com/lok-i/DRLPathPlanner/blob/master/DPP-v1/Test_Model.py) and it should result in the desired visual scene.

**Comment by lok-i** [comment]
Since it has been resolved, am closing this issue.

**Comment by forouzanbeydaghi** [comment]
> Since it has been resolved, am closing this issue.

Thankful

I did not mean the shape of a mini-grid.
 In your program, the red agent is close to the green goal (like the attached photo) and is not exactly in the green target.
But I want it to be exactly in the green goal square (like the previous photo attached).

https://iutbox.iut.ac.ir/index.php/s/BpNqpnzAft5LnJR
